/*
 * Company: ChowDSP
 * Effect Name: Tape Modulation
 * Description: A modulation effect based on a physically-modelled reel-to-reel tape machine.
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#pragma once

#include <Audio.h>
#include <arm_math.h>
#include "Aviate/AudioEffectWrapper.h"

//!s - START_USER_INCLUDES - put your #includes below this line before the matching END
namespace ne_pedal::plugins::tape_mod
{
class TapeModPlugin;
}
//!e - END_USER_INCLUDES

namespace ChowDSP_TapeModulation {

//!s - START_USER_EFFECT_TYPES - put your effect types below this line before the matching END
//!e - END_USER_EFFECT_TYPES

class TapeModulation : public AudioStream, public Aviate::AudioEffectFloat {
public:
    static constexpr unsigned NUM_INPUTS  = 1;
    static constexpr unsigned NUM_OUTPUTS = 1;

    // Some useful aliases
    using AudioBlock    = audio_block_float32_t;
    using AudioDataType = float;

    // List of effect control names
    enum {
        Bypass_e = 0,
        FlutterRate_e = 1,
        FlutterDepth_e = 2,
        WowRate_e = 3,
        WowDepth_e = 4,
        WowVariance_e = 5,
        WowDrift_e = 6,
        Volume_e = 7,
        NUM_CONTROLS
    };

    //!s - START_USER_CLASS_TYPES - put your custom class types below this line before the matching END
    //!e - END_USER_CLASS_TYPES

    TapeModulation();

    //!s - START_USER_CONSTRUCTORS - put your custom constructors below this line before the matching END
    //!e - END_USER_CONSTRUCTORS

    virtual ~TapeModulation();

    // Standard EFX interface functions - do not change these declaration
    virtual void update(); // main audio processing loop function
    void mapMidiControl(int parameter, int midiCC, int midiChannel = 0) override;
    void processMidi(int status, int data1, int data2) override;
    void setParam(int paramIndex, float paramValue) override;
    float getUserParamValue(int paramIndex, float normalizedParamValue);
    const char* getName() override;
    const uint8_t* getRblk() override;

    // control value set functions, must take floats between 0.0f and 1.0f - do not change these declarations
    void flutterrate(float value);
    void flutterdepth(float value);
    void wowrate(float value);
    void wowdepth(float value);
    void wowvariance(float value);
    void wowdrift(float value);
    void volume(float value) override;

    //!s - START_USER_PUBLIC_MEMBERS - put your public members below this line before the matching END
    //!e - END_USER_PUBLIC_MEMBERS

private:
    AudioBlock *m_inputQueueArray[NUM_INPUTS]; // required by AudioStream base class
    int m_midiConfig[NUM_CONTROLS][2]; // stores the midi parameter mapping

    // m_bypass and m_volume are already provided by the base class AudioEffectWrapper or AudioEffectFloat
    float m_flutterrate = 0.0f;
    float m_flutterdepth = 0.0f;
    float m_wowrate = 0.0f;
    float m_wowdepth = 0.0f;
    float m_wowvariance = 0.0f;
    float m_wowdrift = 0.0f;

    audio_block_float32_t* m_basicInputCheck(audio_block_float32_t* inputAudioBlock, unsigned outputChannel);

    //!s - START_USER_PRIVATE_MEMBERS - put your private members below this line before the matching END
        std::unique_ptr<ne_pedal::plugins::tape_mod::TapeModPlugin> plugin;
    //!e - END_USER_PRIVATE_MEMBERS

};

}
